title: gregpaton08
author: Greg Paton
email:
description: > # this means to ignore newlines until "baseurl:"
  Home page for Greg Paton, a software developer working in the Greater Philadelphia and South Jersey area. Passionate about building great software to solve real problems. Feel free to reach out.

twitter_username: gregpaton08
github_username:  gregpaton08

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - projects.html
 - blog.html
 - contact.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  projects:
    output: true

# Google Analytics
google_analytics: UAâ€”105976817-1